### PR TITLE
Added prop to disable the dragging of tabs

### PR DESCRIPTION
**Pull request by erangil2**
Since your tab UI is better than most of the ones I saw online for my needs, I added a property to allow me to disable the dragging, as its behavior is buggy.

### CODE REVIEW

**Comment by georgeOsdDev** [comment]
Thanks!

Can you update some test case and README?

**Comment by georgeOsdDev** [comment]
> disable the dragging

Alternatively you can use your own Tabs component. See #70

**Comment by erangil2** [comment]
I think since you are using 'react-draggable' which allows to disable the dragging, your tabs component should enable using a prop to disable the dragging as well.
I've now added the relevant documentation and tests for the prop.

**Comment by georgeOsdDev** [comment]
Thanks, I will release new version soon.

**Pull request merged**
